# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

In [ ]:
#布尔值，浮点数，整型

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [27]:
import numpy as np
a=np.array([list(range(101,2))])
b=np.array([list(range(100,2))])
c=a-b
print(c.sum())

0.0


1.3  将字符串 s="yoyo" 转换成列表

In [17]:
s ='yoyo'
s=list(s)
print(list(s))

['y', 'o', 'y', 'o']


# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

In [ ]:
#从读取2到99,间隔为3的数字，取最后10个数

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [29]:
class stock:
    def __init__(self,stockName, high, close):
        self.stockName=stockName
        self.close = close
        self.high = high
    def calAmount(self):
        return {self.stockName : self.high-self.close}

one = stock('one_dif', 15,7)
print(one.calAmount())

two = stock('two_dif', 66, 20)
print(two.calAmount())

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [ ]:
#loc[] dtype=()

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [20]:
import pandas as pd
import numpy as np
import talib as ta
stock=pd.read_excel('sz50.xlsx',sheetname='600029.XSHG',index_col='datetime')
NP_stock=np.array(stock)
a = 2/7
Prices = list(range(10))
def ema ( N , Price) :
    if N < 1:
        return Price[0]
    return (1-a)*ema(N-1,Price) + a*Price[N]

print (pd.Series([ema(i,Prices) for i in range(10)]).tail())

FileNotFoundError: [Errno 2] No such file or directory: 'sz50.xlsx'

In [6]:
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
for i in symbol:
    stock=pd.read_excel('sz50.xlsx',sheetname=i,index_col='datetime')
    PN=pd.Panel(stock)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume

3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [7]:
#连着上一题
np_stock=np.array(PN.nidm(3))
price=np.array(PN.close.ndim(2))
print(price.tail(20))

(3, 215, 5)
[[  13.85   13.82   13.83   14.11   14.25   14.39   15.1    15.15   15.22
    14.97   14.89   14.99   14.71   15.07   15.35   16.     16.04   16.29
    16.97   17.05]
 [   8.53    8.56    8.62    8.88    9.25    9.24    9.43    9.25    9.02
     9.15    9.63    9.5     9.9     9.97    9.96    9.49    9.68    9.61
     9.63    9.8 ]
 [ 134.83  134.56  137.5   143.18  143.48  144.15  143.61  143.65  144.35
   143.36  146.41  144.71  148.56  156.53  157.12  157.72  154.99  163.52
   168.58  169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [24]:
arr = np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
